server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: toor
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data: 
   rest:
     base-path: /api
  jackson:    serialization:      fail-on-empty-beans: false
